### ISSUE TITLE
Export Interfaces from src/interfaces.ts

### ISSUE THREAD

**Issue by poozipotti** [Archean-wang/spotify-web-playback-sdk-for-react#1]
Awesome library it's been super helpful. I was wondering if it would be possible to export types like `WebPlaybackTrack`  as I'm passing tracks around to other components it would be super helpful.

**Comment by Archean-wang** [comment]
Wow! I'm glad this could help.
I will do it.

**Comment by Archean-wang** [comment]
@poozipotti Hi! This has been done in v2.0.3

**Comment by poozipotti** [comment]
Thanks man! The repo you made is great super un-opinionated and clean, It's saved me a ton of time
